export * from "./Modals"
/* header */
export * from "./header/HeaderGetData"
export * from "./header/Header"
export * from "./header/AddressBox"
export * from "./header/Address"
export * from "./header/AddressPlaceholder"
export * from "./header/SearchBox"
export * from "./header/Search"
export * from "./header/UserAccount"
export * from "./header/UserProfile"
export * from "./header/UserOrders"
export * from "./header/Orders"
export * from "./header/HeaderServices"

/* Footer */
export * from "./footer/Footer"
export * from "./footer/SocialButton"
export * from "./footer/FirstPageListLinks"
export * from "./footer/SecondPageListLinks"
export * from "./footer/SupportButton"
export * from "./footer/SupportModal"

/* Home Page */
export * from "./homePage/CategorySection"
export * from "./homePage/FoodParty"
export * from "./homePage/slider section/RestaurantSections"
export * from "./homePage/slider section/ResSlider"
export * from "./homePage/slider section/RestaurantSlide"
export * from "./homePage/slider section/RestaurantCard"
export * from "./homePage/slider section/DeliveryType"
export * from "./homePage/DownloadSection"
export * from "./homePage/InputDownloadSection"
export * from "./homePage/Seller"
export * from "./homePage/Cities"

/* Restaurants Page */
export * from "./restaurantPage/PageSorting"
export * from "./restaurantPage/SortingModal"
export * from "./restaurantPage/aside menu/AsideMenu"
export * from "./restaurantPage/aside menu/FoodFilter"
export * from "./restaurantPage/aside menu/ResFilter"
export * from "./restaurantPage/aside menu/PriceFilter"
export * from "./restaurantPage/RestaurantList"

/* Restaurant */
export * from "./restaurant/rightAside/RightAside"
export * from "./restaurant/rightAside/RestaurantInfo"
export * from "./restaurant/rightAside/CategoryNavbar"
export * from "./restaurant/mainSection/FoodMenu"
export * from "./restaurant/mainSection/MenuSection"
export * from "./restaurant/mainSection/CouponSection"
export * from "./restaurant/mainSection/CouponCard"
export * from "./restaurant/mainSection/DiscountSection"
export * from "./restaurant/mainSection/PopularSection"
export * from "./restaurant/mainSection/FoodCard"
export * from "./restaurant/mainSection/FoodPrice"
export * from "./restaurant/mainSection/RegularPrice"
export * from "./restaurant/mainSection/DiscountPrice"
