export * from "./Modals"
export * from "./BreadCrumbs"

/* header */
export * from "./header/HeaderGetData"
export * from "./header/Header"
export * from "./header/AddressBox"
export * from "./header/Address"
export * from "./header/AddressPlaceholder"
export * from "./header/search/SearchBox"
export * from "./header/search/Search"
export * from "./header/UserAccount"
export * from "./header/UserProfile"
export * from "./header/orders/UserOrders"
export * from "./header/orders/Orders"
export * from "./header/HeaderServices"
export * from "./header/search/searchInput"
export * from "./header/search/SearchHistory"
export * from "./header/search/SearchFoods"
export * from "./header/search/SearchCategories"
export * from "./header/search/SearchRestaurants"
export * from "./header/search/SearchFoodsCard"

/* Footer */
export * from "./footer/Footer"
export * from "./footer/SocialButton"
export * from "./footer/FirstPageListLinks"
export * from "./footer/SecondPageListLinks"
export * from "./footer/SupportButton"
export * from "./footer/SupportModal"

/* Home Page */
export * from "./homePage/CategorySection"
export * from "./homePage/food party/FoodParty"
export * from "./homePage/food party/PartySlider"
export * from "./homePage/food party/PartyFoodCard"
export * from "./homePage/food party/PartyCountDown"
export * from "./homePage/slider section/RestaurantSections"
export * from "./homePage/slider section/ResSlider"
export * from "./homePage/slider section/RestaurantSlide"
export * from "./homePage/slider section/RestaurantCard"
export * from "./homePage/slider section/DeliveryType"
export * from "./homePage/DownloadSection"
export * from "./homePage/InputDownloadSection"
export * from "./homePage/Seller"
export * from "./homePage/Cities"

/* Restaurants Page */
export * from "./restaurantPage/PageSorting"
export * from "./restaurantPage/SortingModal"
export * from "./restaurantPage/aside menu/AsideMenu"
export * from "./restaurantPage/aside menu/FoodFilter"
export * from "./restaurantPage/aside menu/ResFilter"
export * from "./restaurantPage/aside menu/PriceFilter"
export * from "./restaurantPage/RestaurantList"

/* Restaurant */
export * from "./restaurants/rightAside/RightAside"
export * from "./restaurants/rightAside/RestaurantInfo"
export * from "./restaurants/rightAside/CategoryNavbar"
export * from "./restaurants/rightAside/ResInfoModal"
export * from "./restaurants/rightAside/ResInfo"
export * from "./restaurants/rightAside/ScoresResInfo"
export * from "./restaurants/rightAside/HeaderBadgeResInfo"
export * from "./restaurants/rightAside/VendorShifts"
export * from "./restaurants/rightAside/CommentSection"
export * from "./restaurants/mainSection/FoodPartyMenu"
export * from "./restaurants/mainSection/FoodMenu"
export * from "./restaurants/mainSection/MenuSection"
export * from "./restaurants/mainSection/CouponSection"
export * from "./restaurants/mainSection/CouponCard"
export * from "./restaurants/mainSection/DiscountSection"
export * from "./restaurants/mainSection/PopularSection"
export * from "./restaurants/mainSection/FoodCard"
export * from "./restaurants/mainSection/FoodPrice"
export * from "./restaurants/mainSection/RegularPrice"
export * from "./restaurants/mainSection/RemainingFoodNumber"
export * from "./restaurants/mainSection/PartyHeader"
export * from "./restaurants/mainSection/SearchFoodResults"
export * from "./restaurants/leftAside/BtnAddToCart"
export * from "./restaurants/leftAside/LeftAside"
export * from "./restaurants/leftAside/DeliveryInfo"
export * from "./restaurants/leftAside/DeliveryInfoModal"
export * from "./restaurants/leftAside/StateBadge"
export * from "./restaurants/leftAside/EmptyCartBasket"
export * from "./restaurants/leftAside/CartBasket"
export * from "./restaurants/leftAside/CartFoodItem"
export * from "./restaurants/leftAside/CartBill"
export * from "./restaurants/leftAside/CartBasketButton"
export * from "./restaurants/foodModals/FoodInfo"
export * from "./restaurants/foodModals/ImageSlider"
export * from "./restaurants/foodModals/Description"