export * from "./Modals"
/* header */
export * from "./header/Header"
export * from "./header/AddressBox"
export * from "./header/Address"
export * from "./header/SearchBox"
export * from "./header/Search"
export * from "./header/UserAccount"
export * from "./header/UserProfile"
export * from "./header/UserOrders"
export * from "./header/Orders"
export * from "./header/HeaderServices"

/* Footer */
export * from "./footer/Footer"
export * from "./footer/SocialButton"
export * from "./footer/FirstPageListLinks"
export * from "./footer/SecondPageListLinks"
export * from "./footer/SupportButton"
export * from "./footer/SupportModal"

/* Home Page */
export * from "./homePage/CategorySection"
export * from "./homePage/FoodParty"
export * from "./homePage/slider section/RestaurantSections"
export * from "./homePage/slider section/ResSlider"
export * from "./homePage/slider section/RestaurantSlide"
export * from "./homePage/slider section/RestaurantCard"
export * from "./homePage/slider section/DeliveryType"
export * from "./homePage/DownloadSection"
export * from "./homePage/InputDownloadSection"
export * from "./homePage/Seller"
export * from "./homePage/Cities"
